import type { Artist, Preferences } from './types';
export const cities = [
  { latitude: 48.8566, longitude: 2.3522, name: 'Paris', country: 'FR' },
  { latitude: 45.764, longitude: 4.8357, name: 'Lyon', country: 'FR' },
  { latitude: 51.5074, longitude: -0.1278, name: 'London', country: 'GB' },
  { latitude: 52.3676, longitude: 4.9041, name: 'Amsterdam', country: 'NL' },
  { latitude: 50.8503, longitude: 4.3517, name: 'Brussels', country: 'BE' },
  { latitude: 52.52, longitude: 13.405, name: 'Berlin', country: 'DE' },
  { latitude: 41.3874, longitude: 2.1686, name: 'Barcelona', country: 'ES' },
  { latitude: 40.4168, longitude: -3.7038, name: 'Madrid', country: 'ES' },
  { latitude: 45.4642, longitude: 9.19, name: 'Milan', country: 'IT' },
];
export const artists: Artist[] = [
  { id: 'fred-again', name: 'Fred again..', genre: 'Electronic', color: '#BA8269', initials: 'fa' },
  {
    id: 'billie-eilish',
    name: 'Billie Eilish',
    genre: 'Alternative',
    color: '#738691',
    initials: 'be',
  },
  {
    id: 'kendrick-lamar',
    name: 'Kendrick Lamar',
    genre: 'Hip-hop',
    color: '#A28258',
    initials: 'kl',
  },
  { id: 'raye', name: 'RAYE', genre: 'R&B / Soul', color: '#867496', initials: 'R' },
  {
    id: 'tame-impala',
    name: 'Tame Impala',
    genre: 'Psychedelic pop',
    color: '#608D80',
    initials: 'ti',
  },
  { id: 'the-weeknd', name: 'The Weeknd', genre: 'R&B / Pop', color: '#A66E78', initials: 'tw' },
  {
    id: 'charli-xcx',
    name: 'Charli xcx',
    genre: 'Electronic / Pop',
    color: '#7C9472',
    initials: 'cx',
  },
  { id: 'sza', name: 'SZA', genre: 'R&B / Soul', color: '#887B64', initials: 'S' },
  { id: 'travis-scott', name: 'Travis Scott', genre: 'Hip-hop', color: '#A27964', initials: 'ts' },
  { id: 'bad-bunny', name: 'Bad Bunny', genre: 'Latin', color: '#8A91A1', initials: 'bb' },
  { id: 'dua-lipa', name: 'Dua Lipa', genre: 'Pop', color: '#98687F', initials: 'dl' },
  {
    id: 'fontaines-dc',
    name: 'Fontaines D.C.',
    genre: 'Alternative',
    color: '#647C98',
    initials: 'fd',
  },
];
export const defaults: Preferences = {
  home: 'Paris',
  scope: 'europe',
  maxHours: null,
  radiusKm: null,
  budget: null,
  notifications: 'important',
  analytics: false,
};
