// Prototype data for the rebrand directions. Fictional sample: dates, prices and travel times are
// invented, exactly like src/domain/sample.ts. Artist photos are the artists' public Spotify images
// (i.scdn.co, the host the app's CSP already allows), loaded at view time, never copied here.
(() => {
  const photo = (hash) => `https://i.scdn.co/image/ab6761610000e5eb${hash}`;

  const demo = [
    {
      id: 'fred-paris',
      artist: 'Fred again..',
      photo: photo('f760292919aee89e58d943d9'),
      mustSee: true,
      reason: 'Must-see for you',
      venue: 'Accor Arena',
      city: 'Paris',
      date: '2026-11-14',
      time: '20:00',
      price: 79,
      status: 'onsale',
      home: true,
      travel: null,
      tour: [
        ['2026-11-14', 'Paris'],
        ['2026-11-18', 'Amsterdam'],
        ['2026-11-22', 'Berlin'],
        ['2026-12-02', 'London'],
      ],
    },
    {
      id: 'charli-paris',
      artist: 'Charli xcx',
      photo: photo('6fa76436a2bba83b9f1d6fd1'),
      reason: 'You follow Charli xcx',
      venue: 'Zénith Paris – La Villette',
      city: 'Paris',
      date: '2026-11-20',
      time: '20:00',
      price: 59,
      status: 'onsale',
      home: true,
      travel: null,
      tour: [
        ['2026-11-20', 'Paris'],
        ['2026-11-24', 'Lyon'],
        ['2026-11-27', 'Barcelona'],
      ],
    },
    {
      id: 'kendrick-ams',
      artist: 'Kendrick Lamar',
      photo: photo('39ba6dcd4355c03de0b50918'),
      mustSee: true,
      reason: 'Must-see for you',
      venue: 'Ziggo Dome',
      city: 'Amsterdam',
      date: '2026-11-26',
      time: '20:30',
      price: 89,
      status: 'onsale',
      home: false,
      travel: { mode: 'train', duration: '3h20', from: 'Paris Nord', to: 'Amsterdam Centraal' },
      tour: [
        ['2026-11-26', 'Amsterdam'],
        ['2026-11-29', 'Cologne'],
        ['2026-12-04', 'Milan'],
      ],
    },
    {
      id: 'billie-paris',
      artist: 'Billie Eilish',
      photo: photo('4a21b4760d2ecb7b0dcdc8da'),
      reason: 'You follow Billie Eilish',
      venue: 'Accor Arena',
      city: 'Paris',
      date: '2026-12-03',
      time: '20:00',
      price: 95,
      status: 'onsale',
      home: true,
      travel: null,
      tour: [
        ['2026-12-03', 'Paris'],
        ['2026-12-05', 'Brussels'],
      ],
    },
    {
      id: 'raye-london',
      artist: 'RAYE',
      photo: photo('d9b6eb671700503c0e6205a9'),
      reason: 'You follow RAYE',
      venue: 'The O2',
      city: 'London',
      date: '2026-12-12',
      time: '19:30',
      price: 65,
      status: 'onsale',
      home: false,
      travel: { mode: 'train', duration: '2h16', from: 'Paris Nord', to: 'London St Pancras' },
      tour: [['2026-12-12', 'London']],
    },
    {
      id: 'tame-bru',
      artist: 'Tame Impala',
      photo: photo('e412a782245eb20d9626c601'),
      reason: 'You follow Tame Impala',
      venue: 'Forest National',
      city: 'Brussels',
      date: '2026-12-28',
      time: '20:00',
      price: 69,
      status: 'onsale',
      home: false,
      travel: { mode: 'train', duration: '1h22', from: 'Paris Nord', to: 'Bruxelles-Midi' },
      tour: [['2026-12-28', 'Brussels']],
    },
    {
      id: 'orelsan-lyon',
      artist: 'Orelsan',
      photo: photo('2b44dbe96b6b8e5261e142b1'),
      reason: 'You follow Orelsan',
      venue: 'LDLC Arena',
      city: 'Lyon',
      date: '2027-01-16',
      time: '20:00',
      price: null,
      status: 'onsale',
      home: false,
      travel: { mode: 'train', duration: '1h56', from: 'Paris Gare de Lyon', to: 'Lyon Part-Dieu' },
      tour: [
        ['2027-01-16', 'Lyon'],
        ['2027-01-23', 'Paris'],
      ],
    },
    {
      id: 'weeknd-milan',
      artist: 'The Weeknd',
      photo: photo('c1719ac9e6a75c1c25835018'),
      reason: 'You follow The Weeknd',
      venue: 'Unipol Forum',
      city: 'Milan',
      date: '2027-02-05',
      time: '21:00',
      price: null,
      status: 'onsale',
      home: false,
      travel: { mode: 'flight', duration: '1h35', from: 'Paris CDG', to: 'Milan Linate' },
      tour: [['2027-02-05', 'Milan']],
    },
  ];

  // break-ui worst case: realistic values that real listings produce, spread across the first rows.
  const worst = [
    {
      id: 'opRF',
      artist: 'Orchestre Philharmonique de Radio France',
      photo: null, // chosen manually, no Spotify image
      reason: 'You follow Orchestre Philharmonique de Radio France',
      venue: 'Philharmonie de Paris – Grande salle Pierre Boulez',
      city: 'Paris',
      date: '2026-10-09',
      time: '20:00',
      price: 35.5,
      status: 'onsale',
      home: true,
      travel: null,
      tour: [['2026-10-09', 'Paris']],
    },
    {
      id: 'mo',
      artist: 'MØ',
      photo: 'https://i.scdn.co/image/ab6761610000e5eb0000000000000000deadbeef', // 404s
      reason: 'You follow MØ',
      venue: 'La Cigale',
      city: 'Paris',
      date: '2026-10-21',
      time: null,
      price: 42,
      status: 'postponed',
      home: true,
      travel: null,
      tour: [],
    },
    {
      id: 'christine',
      artist: 'Christine and the Queens',
      photo: null,
      mustSee: true,
      reason: 'Must-see for you',
      venue: 'Stade Pierre-Mauroy',
      city: "Villeneuve-d'Ascq",
      date: '2026-11-07',
      time: '19:00',
      price: null,
      status: 'onsale',
      home: false,
      travel: { mode: 'train', duration: null, from: 'Paris Nord', to: 'Lille-Europe' }, // no timetable yet
      tour: [['2026-11-07', "Villeneuve-d'Ascq"]],
    },
    {
      id: 'bigflo',
      artist: 'Bigflo & Oli',
      photo: null,
      reason: 'You follow Bigflo & Oli',
      venue: 'Zénith Toulouse Métropole',
      city: 'Toulouse',
      date: '2026-11-19',
      time: '20:00',
      price: 49,
      status: 'cancelled',
      home: false,
      travel: { mode: 'train', duration: '4h18', from: 'Paris Montparnasse', to: 'Toulouse Matabiau' },
      tour: [],
    },
    {
      id: 'weeknd-milan',
      artist: 'The Weeknd',
      photo: photo('c1719ac9e6a75c1c25835018'),
      reason: 'You follow The Weeknd',
      venue: 'Unipol Forum',
      city: 'Milan',
      date: '2027-02-05',
      time: '21:00',
      price: 249.5,
      status: 'onsale',
      home: false,
      travel: { mode: 'flight', duration: '1h35', from: 'Paris CDG', to: 'Milan Linate' },
      tour: [['2027-02-05', 'Milan']],
    },
    {
      id: 'gybe',
      artist: 'Godspeed You! Black Emperor',
      photo: null,
      reason: 'You follow Godspeed You! Black Emperor',
      venue: 'Paradiso',
      city: 'Amsterdam',
      date: '2027-03-14',
      time: '20:00',
      price: null,
      status: 'onsale',
      home: false,
      travel: { mode: 'train', duration: '3h20', from: 'Paris Nord', to: 'Amsterdam Centraal' },
      tour: [],
    },
    demo[0],
  ];

  const params = new URLSearchParams(location.search);
  const mode = ['demo', 'worst', 'empty', 'error'].includes(params.get('data'))
    ? params.get('data')
    : 'demo';

  window.PROTO = {
    mode,
    embed: params.has('embed'),
    home: 'Paris',
    shows: mode === 'worst' ? worst : mode === 'demo' ? demo : [],
    demo,
    providerError:
      mode === 'error'
        ? 'Ticketmaster didn’t answer. Showing nothing rather than old dates.'
        : mode === 'worst'
          ? 'Some listings were last checked 3 hours ago.'
          : null,
    note: 'Sample data. Dates, prices and travel times are fictional.',
  };
})();
